java_binary(
    name = "ImportIOExample",
    srcs = ["ImportIOExample.java"],
    main_class = "ImportIOExample",
    deps = [
        "//external:importio-clientlite-2_0_0-jar",
        "//external:junit-4_8_1-jar",
        "//external:jackson-core-asl-1_9_12-jar",
        "//external:jackson-mapper-asl-1_9_12-jar",
    ]
)
